config/routes.rb
Rails.application.routes.draw do
  root "home#top"
  resources :progresses
  resources :offers
  resources :homes
  resources :apply_posts
  resources :place_posts
  resources :car_posts

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/progresses_controller.rb
class ProgressesController < ApplicationController
  before_action :set_progress, only: [:show, :edit, :update, :destroy]

  # GET /progresses
  # GET /progresses.json
  def index
    @progresses = Progress.all
  end

  # GET /progresses/1
  # GET /progresses/1.json
  def show
  end

  # GET /progresses/new
  def new
    @progress = Progress.new
  end

  # GET /progresses/1/edit
  def edit
  end

  # POST /progresses
  # POST /progresses.json
  def create
    @progress = Progress.new(progress_params)

    respond_to do |format|
      if @progress.save
        format.html { redirect_to @progress, notice: 'Progress was successfully created.' }
        format.json { render :show, status: :created, location: @progress }
      else
        format.html { render :new }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /progresses/1
  # PATCH/PUT /progresses/1.json
  def update
    respond_to do |format|
      if @progress.update(progress_params)
        format.html { redirect_to @progress, notice: 'Progress was successfully updated.' }
        format.json { render :show, status: :ok, location: @progress }
      else
        format.html { render :edit }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /progresses/1
  # DELETE /progresses/1.json
  def destroy
    @progress.destroy
    respond_to do |format|
      format.html { redirect_to progresses_url, notice: 'Progress was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_progress
      @progress = Progress.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def progress_params
      params.require(:progress).permit(
        :progress_offer,
        :progress_interview,
        :progress_contract,
        :progress_training,
        :progress_assignment,
        :progress_name
      )

    end
end

app/helpers/progress_helper.rb
module ProgressHelper
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/views/progresses/_form.html.erb
<%= form_with(model: progress) do |f| %>


  <div class="form-group">
    <%= f.text_field :progress_name, class:"form-control", placeholder:"応募者名"%>
  </div>
  <div class="form-group">
    <%= f.text_field :progress_offer, class:"form-control", placeholder:"オファー"%>
  </div>
  <div class="form-group">
    <%= f.text_field :progress_interview, class: "form-control", placeholder:"面接" %>
  </div>
  <div class="form-group">
    <%= f.text_field :progress_contract, class:"form-control", placeholder:"契約"%>
  </div>
  <div class="form-group">
    <%= f.text_field :progress_training, class:"form-control", placeholder:"研修"%>
  </div>
  <div class="form-group">
    <%= f.text_field :progress_assignment, class:"form-control", placeholder:"配属"%>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/progresses/edit.html.erb
<h1>進捗編集</h1>

<%= render 'form', progress: @progress %>

<button type="button" class="btn btn-outline-primary"><%= link_to '詳細', @progress %></button>
<button type="button" class="btn btn-outline-primary"><%= link_to '戻る', progresses_path %></button>

app/views/progresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>進捗管理</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>応募者名</th>
      <th>オファー</th>
      <th>面接</th>
      <th>契約</th>
      <th>研修</th>
      <th>配属</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @progresses.each do |progress| %>
      <tr>
        <td><%= progress.progress_name %></td>
        <td><%= progress.progress_offer %></td>
        <td><%= progress.progress_interview %></td>
        <td><%= progress.progress_contract %></td>
        <td><%= progress.progress_training %></td>
        <td><%= progress.progress_assignment%></td>
        <td>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            リンク
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to '詳細', progress, class:"btn btn-outline-primary" %>
            <%= link_to '編集', edit_progress_path(progress), class:"btn btn-outline-primary" %>
          </div>
        </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-outline-primary"><%= link_to '新規オファー登録', new_progress_path %></button>

app/views/progresses/new.html.erb
<h1>新規進捗登録</h1>

<%= render 'form', progress: @progress %>

<%= link_to '戻る', progresses_path, class:"btn btn-outline-primary" %>

app/views/progresses/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-hover">
    <tbody>
      <tr>
        <th scope="row">応募者名</th> 
        <td><%= @progress.progress_name %></td>
      </tr>
      <tr>
        <th scope="row">オファー</th> 
        <td><%= @progress.progress_offer %></td>
      </tr>
      <tr>
        <th scope="row">面接</th> 
        <td><%= @progress.progress_interview %></td>
      </tr>
      <tr>
        <th scope="row">契約</th> 
        <td><%= @progress.progress_contract %></td>
      </tr>
      <tr>
        <th scope="row">研修</th> 
        <td><%= @progress.progress_training %></td>
      </tr>
      <tr>
        <th scope="row">配属</th> 
        <td><%= @progress.progress_assignment %></td>
      </tr>
    </tbody>
  </table>

<button type="button" class="btn btn-outline-primary"><%= link_to '戻る', progresses_path %></button>