config/routes.rb
Rails.application.routes.draw do
  root "home#top"
  resources :progresses
  resources :offers
  resources :homes
  resources :apply_posts
  resources :place_posts
  resources :car_posts

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/place_post.rb
class PlacePost < ApplicationRecord
    belongs_to :home, optional: true
end

app/controllers/place_posts_controller.rb
class PlacePostsController < ApplicationController
  before_action :set_place_post, only: [:show, :edit, :update, :destroy]

  # GET /place_posts
  # GET /place_posts.json
  def index
    @place_posts = PlacePost.all
  end

  # GET /place_posts/1
  # GET /place_posts/1.json
  def show
  end

  # GET /place_posts/new
  def new
    @place_post = PlacePost.new
  end

  # GET /place_posts/1/edit
  def edit
  end

  # POST /place_posts
  # POST /place_posts.json
  def create
    @place_post = PlacePost.new(place_post_params)

    respond_to do |format|
      if @place_post.save
        format.html { redirect_to @place_post, notice: 'Place post was successfully created.' }
        format.json { render :show, status: :created, location: @place_post }
      else
        format.html { render :new }
        format.json { render json: @place_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /place_posts/1
  # PATCH/PUT /place_posts/1.json
  def update
    respond_to do |format|
      if @place_post.update(place_post_params)
        format.html { redirect_to @place_post, notice: 'Place post was successfully updated.' }
        format.json { render :show, status: :ok, location: @place_post }
      else
        format.html { render :edit }
        format.json { render json: @place_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /place_posts/1
  # DELETE /place_posts/1.json
  def destroy
    @place_post.destroy
    respond_to do |format|
      format.html { redirect_to place_posts_url, notice: 'Place post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place_post
      @place_post = PlacePost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_post_params
      params.require(:place_post).permit(:place_name, :address)
    end
end

app/helpers/place_posts_helper.rb
module PlacePostsHelper
end

app/views/place_posts/_form.html.erb
<%= form_with(model: place_post) do |form| %>
  <% if place_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place_post.errors.count, "error") %> prohibited this place_post from being saved:</h2>

      <ul>
        <% place_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :place_name %>
    <%= form.text_field :place_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <button type="submit" class="btn btn-outline-primary"><%= form.submit "登録" %></button>
  </div>
<% end %>

app/views/place_posts/edit.html.erb
<h1>Editing Place Post</h1>

<%= render 'form', place_post: @place_post %>

<button type="button" class="btn btn-outline-primary"><%= link_to '詳細', @place_post %></button>
<button type="button" class="btn btn-outline-primary"><%= link_to '戻る', place_posts_path %></button>

app/views/place_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>拠点TOP</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">拠点名</th>
      <th scope="col">住所</>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @place_posts.each do |place_post| %>
      <tr>
        <td><%= place_post.place_name %></td>
        <td><%= place_post.address %></td>
        <td><%= link_to 'Show', place_post, class:"btn btn-outline-primary" %></td>
        <td><%= link_to 'Edit', edit_place_post_path(place_post) %></td>
        <td><%= link_to 'Destroy', place_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-outline-primary"><%= link_to '新規拠点登録', new_place_post_path %></button>

app/views/place_posts/new.html.erb
<h1>新規拠点登録</h1>

<%= render 'form', place_post: @place_post %>

<button type="button" class="btn btn-success"><%= link_to '戻る', place_posts_path %></button>

app/views/place_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>拠点名:</strong>
  <%= @place_post.place_name %>
</p>

<p>
  <strong>住所:</strong>
  <%= @place_post.address %>
</p>

<button type="button" class="btn btn-success"><%= link_to '編集', edit_place_post_path(@place_post) %></button>
<button type="button" class="btn btn-primary"><%= link_to '戻る', place_posts_path %></button>