config/routes.rb
Rails.application.routes.draw do
  root "home#top"
  resources :progresses
  resources :offers
  resources :homes
  resources :apply_posts
  resources :place_posts
  resources :car_posts

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/home.rb
class Home < ApplicationRecord
    has_many :car_posts
    has_many :place_posts
    has_many :apply_posts
    has_many :offers
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @home = Home.all
    @apply_posts = ApplyPost.all.order(created_at: "DESC")
    @car_posts = CarPost.all.order(created_at: "DESC")
    @place_posts = PlacePost.all.order(created_at: "DESC")
    @offers = Offer.all.order(created_at: "DESC")
  end

  def show

  end

  def new
    @home = Home.new
  end

  def edit
  end

  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def home_params
    params.require(:home).permit(

    )
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/top.html.erb
<h1>掲示板TOP</h1>
<br>

<h3>オファー</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>スタート日</th>
      <th>担当部長名</th>
      <th>拠点</th>
    </tr>
  </thead>
  <tbody>
    <% @offers.each do |offer| %>
      <tr class="table-warning">
        <td><%= l offer.offer_start_day, format: :too_short %></td>
        <td><%= offer.offer_tantou %></td>
        <td><%= offer.offer_place %></td>
        <td>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            リンク
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <button type="button" class="btn btn-success"><%= link_to '詳細', offer %></button><br>
            <button type="button" class="btn btn-success"><%= link_to '編集', edit_offer_path(offer) %></button>
          </div>
        </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>




<h3>応募者更新情報</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>更新日時</th>
      <th>応募者名</th>
      <th>住所</th>
      <th>応募日</th>
    </tr>
  </thead>
  <tbody>
    <% @apply_posts.each do |apply_post| %>
      <tr class="table-warning">
        <td><%= l apply_post.created_at, format: :too_short %></td>
        <td><%= apply_post.candidate_name %></td>
        <td><%= apply_post.address %></td>
        <td><%= l apply_post.apply_date, format: :too_short %></td>
        <td>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            リンク
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <button type="button" class="btn btn-success"><%= link_to '詳細', apply_post %></button><br>
            <button type="button" class="btn btn-success"><%= link_to '編集', edit_apply_post_path(apply_post) %></button>
          </div>
        </div>
        </td>     
        </tr>
    <% end %>
  </tbody>
</table>
<br>

<h3>車両更新情報</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>更新日時</th>
      <th>車番</th>
      <th>稼働状況</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @car_posts.each do |car_post| %>
      <tr class="table-warning">
        <td><%= l car_post.created_at, format: :too_short %></td>
        <td><%= car_post.car_number %></td>
        <td><%= car_post.work_or_not %></td>
        <td>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            リンク
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <button type="button" class="btn btn-success"><%= link_to '詳細', car_post %></button><br>
            <button type="button" class="btn btn-success"><%= link_to '編集', edit_car_post_path(car_post) %></button>
          </div>
        </div>
        </td>      
      </tr>
    <% end %>
  </tbody>
</table>
<br>