config/routes.rb
Rails.application.routes.draw do
  root "home#top"
  resources :progresses
  resources :offers
  resources :homes
  resources :apply_posts
  resources :place_posts
  resources :car_posts

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/offer.rb
class Offer < ApplicationRecord
    belongs_to :home, optional: true
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def offer_params
      params.require(:offer).permit(
        :name,
        :offer_start_day,
        :offer_place,
        :offer_course,
        :offer_howmany,
        :offer_tantou
      )
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_with(model: offer) do |f| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
        <% offer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<br>
  <div class="form-group">
    <%= f.label :offer_start_day, "スタート日" %>
    <%= f.date_field :offer_start_day, class:"form-control", placeholder:"スタート日"%>
  </div>
  <div class="form-group">
    <%= f.text_field :offer_place, class: "form-control", placeholder:"拠点名" %>
  </div>
  <div class="form-group">
    <%= f.text_field :offer_course, class:"form-control", placeholder:"コース数"%>
  </div>
  <div class="form-group">
    <%= f.text_field :offer_howmany, class:"form-control", placeholder:"人数"%>
  </div>
  <div class="form-group">
    <%= f.text_field :offer_tantou, class:"form-control", placeholder:"担当部長名(何月に依頼があったかここに記載)"%>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>オファー編集</h1>

<%= render 'form', offer: @offer %>

<%= link_to '詳細', @offer, class:"btn btn-outline-primary" %> 
<%= link_to 'Back', offers_path, class:"btn btn-outline-primary" %>

app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>オファー管理</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>記載日時</th>
      <th>スタート日</th>
      <th>拠点</th>
      <th>コース数</th>
      <th>人数</th>
      <th>担当部長名</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= l offer.created_at, format: :short %></td>
        <td><%= l offer.offer_start_day, format: :too_short %></td>
        <td><%= offer.offer_place %></td>
        <td><%= offer.offer_course %></td>
        <td><%= offer.offer_howmany %>人</td>
        <td><%= offer.offer_tantou %></td>
        <td>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            リンク
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to '詳細', offer, class:"btn btn-outline-primary" %><br>
            <%= link_to '編集', edit_offer_path(offer), class:"btn btn-outline-primary" %><br>
            <%= link_to '削除', offer, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-primary" %>
          </div>
        </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-outline-primary"><%= link_to '新規オファー登録', new_offer_path %></button>

app/views/offers/new.html.erb
<h1>新規オファー</h1>

<%= render 'form', offer: @offer %>

<%= link_to '戻る', offers_path, class:"btn btn-outline-primary" %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<h1>オファー詳細</h1>

<br>
<table class="table table-hover">
    <tbody>
      <tr>
        <th scope="row">スタート日</th> 
        <td><%= l @offer.offer_start_day, format: :too_short %></td>
      </tr>
      <tr>
        <th scope="row">拠点名</th> 
        <td><%= @offer.offer_place %></td>
      </tr>
      <tr>
        <th scope="row">コース数</th> 
        <td><%= @offer.offer_course %></td>
      </tr>
      <tr>
        <th scope="row">人数</th> 
        <td><%= @offer.offer_howmany %></td>
      </tr>
      <tr>
        <th scope="row">担当部長名</th> 
        <td><%= @offer.offer_tantou %></td>
      </tr>
    </tbody>
  </table>

<button type="button" class="btn btn-outline-primary"><%= link_to '編集', edit_offer_path(@offer) %></button>
<button type="button" class="btn btn-outline-primary"><%= link_to '戻る', offers_path %></button>